# -*- coding: utf-8 -*-

import re, ast, tempfile
from pathlib import Path
from typing import Optional
from dataclasses import dataclass, field

@dataclass
class ExtractedModel:
    software: str = ""
    file_path: str = ""
    template_name: str = ""
    geometry_type: str = ""
    dimension: str = "3D"
    geometry_params: dict = field(default_factory=dict)
    physics_interfaces: list = field(default_factory=list)
    physics_type: str = ""
    materials: list = field(default_factory=list)
    boundary_conditions: list = field(default_factory=list)
    mesh_type: str = ""
    mesh_params: dict = field(default_factory=dict)
    study_type: str = ""
    study_params: dict = field(default_factory=dict)
    plots: list = field(default_factory=list)
    exports: list = field(default_factory=list)
    raw_notes: list = field(default_factory=list)
    extraction_confidence: str = "medium"

    def to_template_yaml(self):
        L = []
        L.append('# Auto-generated from: ' + self.file_path)
        L.append('# Generated by sim-agent-platform ModelLearner')
        L.append('# Confidence: ' + self.extraction_confidence)
        L.append('')
        L.append('meta:')
        L.append('  name: ' + chr(34) + self.template_name + chr(34))
        L.append('  domain: ' + self._infer_domain())
        L.append('  physics_type: ' + (self.physics_type or 'unknown'))
        L.append('  dimension: ' + self.dimension)
        L.append('  common_pitfalls: []')
        L.append('')
        L.append('geometry:')
        L.append('  type: ' + (self.geometry_type or 'unknown'))
        L.append('  params:')
        for k, v in self.geometry_params.items():
            L.append('    ' + k + ': {symbol: ' + k + ', default: ' + chr(34) + str(v) + chr(34) + ', description: ' + chr(34) + chr(34) + '}')
        L.append('')
        L.append('physics:')
        L.append('  interfaces: ' + str(self.physics_interfaces))
        L.append('')
        L.append('boundary_conditions:')
        for bc in self.boundary_conditions:
            L.append('  - type: ' + bc.get('type', 'unknown'))
        L.append('')
        L.append('materials:')
        for m in self.materials:
            L.append('  - name: ' + m.get('name', 'unknown'))
        L.append('')
        L.append('mesh:')
        L.append('  type: ' + (self.mesh_type or 'free_triangular'))
        L.append('')
        L.append('study:')
        L.append('  type: ' + (self.study_type or 'stationary'))
        L.append('')
        L.append('postprocessing:')
        for p in self.plots:
            L.append('  - plot: ' + p)
        return chr(10).join(L)

    def _infer_domain(self):
        p = self.physics_type.lower()
        if 'electromagnetic' in p:
            return 'photonic_crystal' if self.study_type == 'eigenfrequency' else 'electromagnetic'
        if 'heat' in p:
            return 'thermal'
        if 'solid' in p:
            return 'structural'
        return 'unknown'


class ComsolScriptExtractor:
    SOFTWARE = 'COMSOL Python script'

    def extract(self, script_path):
        src = open(script_path, 'r', encoding='utf-8').read()
        e = ExtractedModel(software=self.SOFTWARE, file_path=str(script_path), template_name=Path(script_path).stem)
        try:
            tree = ast.parse(src)
        except SyntaxError:
            e.extraction_confidence = 'low'
            return e
        v = _Visitor(e)
        v.visit(tree)
        if v.has_eigen:
            e.study_type = 'eigenfrequency'
        elif v.has_stationary:
            e.study_type = 'stationary'
        if v.has_em:
            e.physics_type = 'electromagnetic_waves'
        elif v.has_heat:
            e.physics_type = 'heat_transfer'
        if v.has_periodic:
            e.boundary_conditions.append({'type': 'PeriodicCondition'})
        e.dimension = '3D' if v.has_3d else '2D'
        for k, val in v.params.items():
            e.geometry_params[k] = val
        e.extraction_confidence = 'medium' if e.physics_type else 'low'
        return e


class _Visitor(ast.NodeVisitor):
    def __init__(self, e):
        self.e = e
        self.params = {}
        self.has_eigen = False
        self.has_stationary = False
        self.has_em = False
        self.has_heat = False
        self.has_periodic = False
        self.has_3d = False

    def visit_Assign(self, n):
        if isinstance(n.targets[0], ast.Name):
            nm = n.targets[0].id
            if isinstance(n.value, ast.Constant):
                self.params[nm] = str(n.value.value)
            elif isinstance(n.value, ast.BinOp) and isinstance(n.value.left, ast.Constant):
                self.params[nm] = str(n.value.left.value) + '*...'
        self.generic_visit(n)

    def visit_Call(self, n):
        fl = ''
        if isinstance(n.func, ast.Attribute):
            fl = n.func.attr
        elif isinstance(n.func, ast.Name):
            fl = n.func.id
        fl = fl.lower()
        if 'eigen' in fl:
            self.has_eigen = True
        if 'station' in fl or 'static' in fl:
            self.has_stationary = True
        if 'ewfd' in fl or 'electromagnetic' in fl:
            self.has_em = True
        if 'ht' in fl or 'heat' in fl:
            self.has_heat = True
        if 'periodic' in fl or 'bloch' in fl:
            self.has_periodic = True
        for a in n.args:
            if isinstance(a, ast.Constant):
                if a.value == 3:
                    self.has_3d = True
                if isinstance(a.value, str):
                    s = a.value.lower()
                    if any(k in s for k in ['eigen', 'modal']):
                        self.has_eigen = True
                    if any(k in s for k in ['station', 'static']):
                        self.has_stationary = True
                    if any(k in s for k in ['electromagnetic', 'ewfd', 'wave']):
                        self.has_em = True
                    if any(k in s for k in ['heat', 'thermal', 'ht']):
                        self.has_heat = True
                    if any(k in s for k in ['periodic', 'bloch']):
                        self.has_periodic = True
        self.generic_visit(n)


class ModelLearner:

    def __init__(self):
        self._ext = {'.py': ComsolScriptExtractor()}

    def register(self, ext, extractor):
        self._ext[ext.lower()] = extractor

    def learn_from(self, file_path, output_dir=None):
        p = Path(file_path)
        if not p.exists():
            return {'success': False, 'error': 'File not found: ' + str(file_path)}
        ex = self._ext.get(p.suffix.lower())
        if ex is None:
            return {'success': False, 'error': 'Unsupported format: ' + p.suffix, 'supported': list(self._ext.keys())}
        try:
            e = ex.extract(p)
            yml = e.to_template_yaml()
            sp = None
            if output_dir:
                od = Path(output_dir)
                od.mkdir(parents=True, exist_ok=True)
                sf = od / (e.template_name + '_learned.yaml')
                sf.write_text(yml, encoding='utf-8')
                sp = str(sf)
            return {'success': True, 'template_yaml': yml, 'extracted': e, 'saved_path': sp}
        except Exception as ex:
            return {'success': False, 'error': str(ex)}

    def supported_formats(self):
        return list(self._ext.keys())


def demo():
    src = 'import mph' + chr(10)
    src += 'a = 1e-6' + chr(10)
    src += 'R = 0.2 * a' + chr(10)
    src += 'epsilon_rod = 11.7' + chr(10)
    src += 'model = client.create("wu_hu")' + chr(10)
    src += 'comp = model.java.component().create("comp1", True)' + chr(10)
    src += 'geom = comp.geom().create("geom1", 2)' + chr(10)
    src += 'physics = comp.physics().create("ewfd", "ElectromagneticWavesFrequencyDomain", "geom1")' + chr(10)
    src += 'pbc = physics.create("pbc1", "PeriodicCondition")' + chr(10)
    src += 'mesh = comp.mesh().create("mesh1")' + chr(10)
    src += 'mesh.run()' + chr(10)
    src += 'study = model.java.study().create("std1")' + chr(10)
    src += 'eig = study.create("eig1", "Eigenfrequency")' + chr(10)
    src += 'eig.set("neigs", "8")' + chr(10)

    tf = tempfile.NamedTemporaryFile(suffix='.py', mode='w', encoding='utf-8', delete=False)
    tf.write(src)
    tf.close()

    lr = ModelLearner()
    r = lr.learn_from(tf.name)
    print('=' * 60)
    print('ModelLearner Demo')
    print('=' * 60)
    print('Success:', r['success'])
    if r['success']:
        e = r['extracted']
        print('Name:', e.template_name)
        print('Study:', e.study_type)
        print('Physics:', e.physics_type)
        print('Periodic:', e.boundary_conditions)
        print('Params:', e.geometry_params)
        print('Confidence:', e.extraction_confidence)
        print()
        print(r['template_yaml'][:500])

    import os
    os.unlink(tf.name)


if __name__ == '__main__':
    demo()


# ---- COMSOL .mph Extractor (requires mph library) ----

class ComsolMphExtractor:
    SOFTWARE = 'COMSOL Multiphysics'

    def extract(self, mph_path):
        e = ExtractedModel(software=self.SOFTWARE, file_path=str(mph_path), template_name=Path(mph_path).stem)
        try:
            import mph
        except ImportError:
            e.raw_notes.append('mph library not installed: pip install mph')
            e.extraction_confidence = 'low'
            return e
        try:
            client = mph.Client()
            model = client.load(str(mph_path.absolute()))
            try:
                e.physics_interfaces = model.physics()
                for pn in e.physics_interfaces:
                    pl = pn.lower()
                    if any(k in pl for k in ['ewfd', 'electromagnetic', 'wave']):
                        e.physics_type = 'electromagnetic_waves'
                    elif any(k in pl for k in ['ht', 'heat']):
                        e.physics_type = 'heat_transfer'
                    elif any(k in pl for k in ['solid', 'struct']):
                        e.physics_type = 'solid_mechanics'
            except: pass
            try:
                params = model.parameters()
                for k, v in params.items():
                    e.geometry_params[k] = str(v)
            except: pass
            try:
                studies = model.studies()
                if studies:
                    sn = studies[0].lower()
                    if 'eigen' in sn: e.study_type = 'eigenfrequency'
                    elif 'station' in sn or 'static' in sn: e.study_type = 'stationary'
                    elif 'time' in sn or 'transient' in sn: e.study_type = 'time_dependent'
            except: pass
            try:
                e.plots = list(model.plots())
            except: pass
            e.extraction_confidence = 'high' if e.physics_interfaces else 'medium'
            client.clear()
        except Exception as ex:
            e.raw_notes.append('Extraction failed: ' + str(ex))
            e.extraction_confidence = 'low'
        return e


# Register COMSOL mph extractor in ModelLearner
ModelLearner.__init__ = lambda self: setattr(self, '_ext', {'.py': ComsolScriptExtractor(), '.mph': ComsolMphExtractor()})
ModelLearner.register = lambda self, ext, ex: self._ext.__setitem__(ext.lower(), ex)
ModelLearner.learn_from = ModelLearner.learn_from
ModelLearner.supported_formats = ModelLearner.supported_formats
